version: '3'
services:
  rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"  # RTMP
      - "8080:80"    # HTTP
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  rtsp:
    image: aler9/rtsp-simple-server
    ports:
      - "8554:8554"  # RTSP
